region = "us-east-1"
customer_name = "ten"
project = "ten"
repository_url = "https://github.com/craffapptest1/default_user_portfolio00700.git"
branch = "master"
db_password = "ten_password"
db_username = "postgres"
db_name = "ten_db"
